import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const kanitRegular = localFont({
  src: "./fonts/Inconsolata-Medium.ttf",
  variable: "--font-kanit-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Jordan Barton's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanitRegular.variable} antialiased`}>{children}</body>
    </html>
  );
}
